- alias: unit8_switch_toggle
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Кнопка подключенная через шлюз
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.switch_158d00010b1963
       click_type: single
# Кнопка подключенная через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000154a353_click
     to: 'single'
  action:
   - service: switch.toggle
     entity_id: switch.0x00158d0001fa2934_switch
     
- alias: unit8_light_on_day
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Выключатель подключенный через шлюз
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.wall_switch_right_158d0001f47e10
       click_type: single
# Выключатель подключенный через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000282a130_click
     to: 'right' 
# Датчик движения подключенный через шлюз
   - platform: event
     event_type: xiaomi_aqara.motion
     event_data:
       entity_id: binary_sensor.motion_sensor_158d0001e16204
# Датчик движения подключенный через zigbe2mqtt
   - platform: state
     entity_id: binary_sensor.0x00158d0001e547a3_occupancy
     to: 'on'
  condition:
   - condition: state
     entity_id: light.yeelight_450
     state: 'off' 
   - condition: time
     after: '08:00:00'
     before: '21:00:00'
  action:
   - service: light.turn_on
     entity_id: light.yeelight_450
     data_template:
       brightness_pct: 100
       kelvin: 4000
       
- alias: unit8_light_on_night
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Выключатель подключенный через шлюз
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.wall_switch_right_158d0001f47e10
       click_type: single
# Выключатель подключенный через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000282a130_click
     to: 'right'       
# Датчик движения подключенный через шлюз
   - platform: event
     event_type: xiaomi_aqara.motion
     event_data:
       entity_id: binary_sensor.motion_sensor_158d0001e16204
# Датчик движения подключенный через zigbe2mqtt
   - platform: state
     entity_id: binary_sensor.0x00158d0001e547a3_occupancy
     to: 'on'
  condition:
   - condition: state
     entity_id: light.yeelight_450
     state: 'off'
   - condition: time
     after: '21:00:00'
     before: '08:00:00'
  action:
   - service: light.turn_on
     entity_id: light.yeelight_450
     data_template:
       brightness_pct: 50
       kelvin: 4000
       
- alias: unit8_light_off
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Выключатель подключенный через шлюз
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.wall_switch_right_158d0001f47e10
       click_type: single
# Выключатель подключенный через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000282a130_click
     to: 'right' 
# Датчик движения подключенный через шлюз
   - platform: state
     entity_id: binary_sensor.motion_sensor_158d0001e16204
     to: 'off'
     for:
       minutes: 3  
# Датчик движения подключенный через zigbe2mqtt
   - platform: state
     entity_id: binary_sensor.0x00158d0001e547a3_occupancy
     to: 'off'
     for:
       minutes: 3
  condition:
   - condition: state
     entity_id: light.yeelight_450
     state: 'on'
  action:
   - service: light.turn_off
     entity_id: light.yeelight_450
     
- alias: unit8_vent_on
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Выключатель подключенный через шлюз 
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.wall_switch_both_158d00013fc3bc
       click_type: both
# Выключатель подключенный через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000282a130_click
     to: 'both' 
## Влажность более 70 процентов
   - platform: numeric_state
     entity_id: sensor.0x00158d0001dcd47e_humidity
     above: 70
  condition:
   - condition: state
     entity_id: switch.0x00158d0001117040_switch_left
     state: 'off'
  action:
   - service: timer.start
     entity_id: timer.vent
   - service: switch.turn_on
     entity_id: switch.0x00158d0001117040_switch_left
     
- alias: unit8_vent_off
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Выключатель подключенный через шлюз 
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.wall_switch_both_158d00013fc3bc
       click_type: both
# Выключатель подключенный через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000282a130_click
     to: 'both' 
## Завершение таймера
   - platform: event
     event_type: timer.finished
     event_data:
       entity_id: timer.vent
  condition:
   - condition: state
     entity_id: switch.0x00158d0001117040_switch_left
     state: 'on'
  action:
   - service: timer.cancel
     entity_id: timer.vent
   - service: switch.turn_off
     entity_id: switch.0x00158d0001117040_switch_left
     
- alias: unit8_light_auto_off_unavailable
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
   - platform: state
     entity_id: light.philips_ceiling
     from: 'unavailable'
     to: 'on'
  action:
    - service: light.turn_off
      entity_id: light.philips_ceiling   

- alias: unit8_light
#   initial_state: true - опция для автоматической активации автоматизации
  initial_state: false
  trigger:
# Выключатель подключенный через шлюз
   - platform: event
     event_type: xiaomi_aqara.click
     event_data:
       entity_id: binary_sensor.wall_switch_right_158d0001f47e10
       click_type: single
# Выключатель подключенный через zigbe2mqtt
   - platform: state
     entity_id: sensor.0x00158d000282a130_click
     to: 'right'     
  action: 
  - service: script.turn_on
    data_template:
     entity_id: >-
        {%- if states.light.yeelight_450.state  == 'off' -%}
        script.unit8_light_on_full
        {%- elif states.light.yeelight_450.state  == 'on' -%}
        script.unit8_light_off
        {%- endif -%}   